const notes =
{
	'1': { 'keyNumber': 1, 'key': ['A'], 'color': 'w', 'oct': 0, 'asc': '' },
	'2': { 'keyNumber': 2, 'key': ['A♯', 'B♭'], 'color': 'b', 'oct': 0, 'asc': '' },
	'3': { 'keyNumber': 3, 'key': ['B'], 'color': 'w', 'oct': 0, 'asc': '' },

	'4': { 'keyNumber': 4, 'key': ['C'], 'color': 'w', 'oct': 1, 'asc': '' },
	'5': { 'keyNumber': 5, 'key': ['C♯', 'D♭'], 'color': 'b', 'oct': 1, 'asc': '' },
	'6': { 'keyNumber': 6, 'key': ['D'], 'color': 'w', 'oct': 1, 'asc': '' },
	'7': { 'keyNumber': 7, 'key': ['D♯', 'E♭'], 'color': 'b', 'oct': 1, 'asc': '' },
	'8': { 'keyNumber': 8, 'key': ['E'], 'color': 'w', 'oct': 1, 'asc': '' },
	'9': { 'keyNumber': 9, 'key': ['F'], 'color': 'w', 'oct': 1, 'asc': '' },
	'10': { 'keyNumber': 10, 'key': ['F♯', 'G♭'], 'color': 'b', 'oct': 1, 'asc': '' },
	'11': { 'keyNumber': 11, 'key': ['G'], 'color': 'w', 'oct': 1, 'asc': '' },
	'12': { 'keyNumber': 12, 'key': ['G♯', 'A♭'], 'color': 'b', 'oct': 1, 'asc': '' },
	'13': { 'keyNumber': 13, 'key': ['A'], 'color': 'w', 'oct': 1, 'asc': '' },
	'14': { 'keyNumber': 14, 'key': ['A♯', 'B♭'], 'color': 'b', 'oct': 1, 'asc': '' },
	'15': { 'keyNumber': 15, 'key': ['B'], 'color': 'w', 'oct': 1, 'asc': '' },

	'16': { 'keyNumber': 16, 'key': ['C'], 'color': 'w', 'oct': 2, 'asc': '' },
	'17': { 'keyNumber': 17, 'key': ['C♯', 'D♭'], 'color': 'b', 'oct': 2, 'asc': '' },
	'18': { 'keyNumber': 18, 'key': ['D'], 'color': 'w', 'oct': 2, 'asc': '' },
	'19': { 'keyNumber': 19, 'key': ['D♯', 'E♭'], 'color': 'b', 'oct': 2, 'asc': '' },
	'20': { 'keyNumber': 20, 'key': ['E'], 'color': 'w', 'oct': 2, 'asc': '' },
	'21': { 'keyNumber': 21, 'key': ['F'], 'color': 'w', 'oct': 2, 'asc': '' },
	'22': { 'keyNumber': 22, 'key': ['F♯', 'G♭'], 'color': 'b', 'oct': 2, 'asc': '' },
	'23': { 'keyNumber': 23, 'key': ['G'], 'color': 'w', 'oct': 2, 'asc': '' },
	'24': { 'keyNumber': 24, 'key': ['G♯', 'A♭'], 'color': 'b', 'oct': 2, 'asc': '' },
	'25': { 'keyNumber': 25, 'key': ['A'], 'color': 'w', 'oct': 2, 'asc': '' },
	'26': { 'keyNumber': 26, 'key': ['A♯', 'B♭'], 'color': 'b', 'oct': 2, 'asc': '' },
	'28': { 'keyNumber': 27, 'key': ['B'], 'color': 'w', 'oct': 2, 'asc': '' },

	'29': { 'keyNumber': 29, 'key': ['C'], 'color': 'w', 'oct': 3, 'asc': '' },
	'30': { 'keyNumber': 30, 'key': ['C♯', 'D♭'], 'color': 'b', 'oct': 3, 'asc': '' },
	'31': { 'keyNumber': 31, 'key': ['D'], 'color': 'w', 'oct': 3, 'asc': '' },
	'32': { 'keyNumber': 32, 'key': ['D♯', 'E♭'], 'color': 'b', 'oct': 3, 'asc': '' },
	'33': { 'keyNumber': 33, 'key': ['E'], 'color': 'w', 'oct': 3, 'asc': '' },
	'34': { 'keyNumber': 34, 'key': ['F'], 'color': 'w', 'oct': 3, 'asc': '' },
	'35': { 'keyNumber': 35, 'key': ['F♯', 'G♭'], 'color': 'b', 'oct': 3, 'asc': '' },
	'36': { 'keyNumber': 36, 'key': ['G'], 'color': 'w', 'oct': 3, 'asc': '' },
	'37': { 'keyNumber': 37, 'key': ['G♯', 'A♭'], 'color': 'b', 'oct': 3, 'asc': '' },
	'38': { 'keyNumber': 38, 'key': ['A'], 'color': 'w', 'oct': 3, 'asc': '72' },
	'39': { 'keyNumber': 39, 'key': ['A♯', 'B♭'], 'color': 'b', 'oct': 3, 'asc': '85' },
	'40': { 'keyNumber': 40, 'key': ['B'], 'color': 'w', 'oct': 3, 'asc': '74' },

	'41': { 'keyNumber': 41, 'key': ['C'], 'color': 'w', 'oct': 4, 'asc': '65' },
	'42': { 'keyNumber': 42, 'key': ['C♯', 'D♭'], 'color': 'b', 'oct': 4, 'asc': '87' },
	'43': { 'keyNumber': 43, 'key': ['D'], 'color': 'w', 'oct': 4, 'asc': '83' },
	'44': { 'keyNumber': 44, 'key': ['D♯', 'E♭'], 'color': 'b', 'oct': 4, 'asc': '69' },
	'45': { 'keyNumber': 45, 'key': ['E'], 'color': 'w', 'oct': 4, 'asc': '68' },
	'46': { 'keyNumber': 46, 'key': ['F'], 'color': 'w', 'oct': 4, 'asc': '70' },
	'47': { 'keyNumber': 47, 'key': ['F♯', 'G♭'], 'color': 'b', 'oct': 4, 'asc': '84' },
	'48': { 'keyNumber': 48, 'key': ['G'], 'color': 'w', 'oct': 4, 'asc': '71' },
	'49': { 'keyNumber': 49, 'key': ['G♯', 'A♭'], 'color': 'b', 'oct': 4, 'asc': '89' },
	'50': { 'keyNumber': 50, 'key': ['A'], 'color': 'w', 'oct': 4, 'asc': '' },
	'51': { 'keyNumber': 51, 'key': ['A♯', 'B♭'], 'color': 'b', 'oct': 4, 'asc': '' },
	'52': { 'keyNumber': 52, 'key': ['B'], 'color': 'w', 'oct': 4, 'asc': '' },

	'53': { 'keyNumber': 53, 'key': ['C'], 'color': 'w', 'oct': 5, 'asc': '' },
	'54': { 'keyNumber': 54, 'key': ['C♯', 'D♭'], 'color': 'b', 'oct': 5, 'asc': '' },
	'55': { 'keyNumber': 55, 'key': ['D'], 'color': 'w', 'oct': 5, 'asc': '' },
	'56': { 'keyNumber': 56, 'key': ['D♯', 'E♭'], 'color': 'b', 'oct': 5, 'asc': '' },
	'57': { 'keyNumber': 57, 'key': ['E'], 'color': 'w', 'oct': 5, 'asc': '' },
	'58': { 'keyNumber': 58, 'key': ['F'], 'color': 'w', 'oct': 5, 'asc': '' },
	'59': { 'keyNumber': 59, 'key': ['F♯', 'G♭'], 'color': 'b', 'oct': 5, 'asc': '' },
	'60': { 'keyNumber': 60, 'key': ['G'], 'color': 'w', 'oct': 5, 'asc': '' },
	'61': { 'keyNumber': 61, 'key': ['G♯', 'A♭'], 'color': 'b', 'oct': 5, 'asc': '' },
	'62': { 'keyNumber': 62, 'key': ['A'], 'color': 'w', 'oct': 5, 'asc': '' },
	'63': { 'keyNumber': 63, 'key': ['A♯', 'B♭'], 'color': 'b', 'oct': 5, 'asc': '' },
	'64': { 'keyNumber': 64, 'key': ['B'], 'color': 'w', 'oct': 5, 'asc': '' },

	'65': { 'keyNumber': 65, 'key': ['C'], 'color': 'w', 'oct': 6, 'asc': '' },
	'66': { 'keyNumber': 66, 'key': ['C♯', 'D♭'], 'color': 'b', 'oct': 6, 'asc': '' },
	'67': { 'keyNumber': 67, 'key': ['D'], 'color': 'w', 'oct': 6, 'asc': '' },
	'68': { 'keyNumber': 68, 'key': ['D♯', 'E♭'], 'color': 'b', 'oct': 6, 'asc': '' },
	'69': { 'keyNumber': 69, 'key': ['E'], 'color': 'w', 'oct': 6, 'asc': '' },
	'70': { 'keyNumber': 70, 'key': ['F'], 'color': 'w', 'oct': 6, 'asc': '' },
	'71': { 'keyNumber': 71, 'key': ['F♯', 'G♭'], 'color': 'b', 'oct': 6, 'asc': '' },
	'72': { 'keyNumber': 72, 'key': ['G'], 'color': 'w', 'oct': 6, 'asc': '' },
	'73': { 'keyNumber': 73, 'key': ['G♯', 'A♭'], 'color': 'b', 'oct': 6, 'asc': '' },
	'74': { 'keyNumber': 74, 'key': ['A'], 'color': 'w', 'oct': 6, 'asc': '' },
	'75': { 'keyNumber': 75, 'key': ['A♯', 'B♭'], 'color': 'b', 'oct': 6, 'asc': '' },
	'76': { 'keyNumber': 76, 'key': ['B'], 'color': 'w', 'oct': 6, 'asc': '' },

	'77': { 'keyNumber': 77, 'key': ['C'], 'color': 'w', 'oct': 1, 'asc': '' },
	'78': { 'keyNumber': 78, 'key': ['C♯', 'D♭'], 'color': 'b', 'oct': 1, 'asc': '' },
	'79': { 'keyNumber': 79, 'key': ['D'], 'color': 'w', 'oct': 1, 'asc': '' },
	'80': { 'keyNumber': 80, 'key': ['D♯', 'E♭'], 'color': 'b', 'oct': 1, 'asc': '' },
	'81': { 'keyNumber': 81, 'key': ['E'], 'color': 'w', 'oct': 1, 'asc': '' },
	'82': { 'keyNumber': 82, 'key': ['F'], 'color': 'w', 'oct': 1, 'asc': '' },
	'83': { 'keyNumber': 83, 'key': ['F♯', 'G♭'], 'color': 'b', 'oct': 1, 'asc': '' },
	'84': { 'keyNumber': 84, 'key': ['G'], 'color': 'w', 'oct': 1, 'asc': '' },
	'85': { 'keyNumber': 85, 'key': ['G♯', 'A♭'], 'color': 'b', 'oct': 1, 'asc': '' },
	'86': { 'keyNumber': 86, 'key': ['A'], 'color': 'w', 'oct': 1, 'asc': '' },
	'87': { 'keyNumber': 87, 'key': ['A♯', 'B♭'], 'color': 'b', 'oct': 1, 'asc': '' },
	'88': { 'keyNumber': 88, 'key': ['B'], 'color': 'w', 'oct': 1, 'asc': '' }
};

export { notes };